//    (The MIT License)
//
//    Copyright (c) 2012 Richard S Allinson <rsa@mountainmansoftware.com>
//
//    Permission is hereby granted, free of charge, to any person obtaining
//    a copy of this software and associated documentation files (the
//    "Software"), to deal in the Software without restriction, including
//    without limitation the rights to use, copy, modify, merge, publish,
//    distribute, sublicense, and/or sell copies of the Software, and to
//    permit persons to whom the Software is furnished to do so, subject to
//    the following conditions:
//
//    The above copyright notice and this permission notice shall be
//    included in all copies or substantial portions of the Software.
//
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
//    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
//    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#include <SimpleTimer.h>
#include <Rainbowduino.h>

SimpleTimer timer;

const int EMPTY = 0;
const int START = 7;
const int END = -6;

uint32_t color = (uint32_t)0x00FF00; // RRGGBB

int queue[256] = {};
int lastAdded = 0;
int lastRead = 0;

char *WORDS[584] = {
    "aardvark",
    "account",
    "acrylic",
    "activity",
    "addition",
    "advantage",
    "africa",
    "afterthought",
    "air",
    "airport",
    "alcohol",
    "alley",
    "alphabet",
    "ambulance",
    "anatomy",
    "angora",
    "answer",
    "antelope",
    "apology",
    "appendix",
    "april",
    "archeology",
    "argentina",
    "arm",
    "army",
    "ashtray",
    "asterisk",
    "atom",
    "attic",
    "australia",
    "authority",
    "baboon",
    "bacon",
    "bagel",
    "baker",
    "ball",
    "band",
    "banjo",
    "bar",
    "baritone",
    "basement",
    "bass",
    "bathroom",
    "bay",
    "bean",
    "beat",
    "bed",
    "beef",
    "beggar",
    "belgian",
    "belt",
    "berry",
    "bicycle",
    "biology",
    "birth",
    "black",
    "blinker",
    "blouse",
    "board",
    "bolt",
    "bongo",
    "booklet",
    "bottle",
    "bowl",
    "bra",
    "brake",
    "brass",
    "breakfast",
    "bridge",
    "broker",
    "brow",
    "bucket",
    "bugle",
    "bulldozer",
    "burma",
    "bush",
    "butter",
    "cabinet",
    "cake",
    "calf",
    "camp",
    "cancer",
    "canvas",
    "capricorn",
    "caravan",
    "cardigan",
    "carp",
    "cart",
    "castanet",
    "cathedral",
    "cause",
    "cd",
    "cell",
    "cement",
    "century",
    "chain",
    "change",
    "charles",
    "cheese",
    "cheque",
    "chest",
    "chief",
    "chime",
    "chinese",
    "christmas",
    "cicada",
    "cirrus",
    "clarinet",
    "clef",
    "climb",
    "close",
    "cloudy",
    "coach",
    "cobweb",
    "cod",
    "coke",
    "collision",
    "color",
    "comb",
    "command",
    "company",
    "composer",
    "condor",
    "congo",
    "continent",
    "copper",
    "cork",
    "correspondent",
    "cougar",
    "court",
    "cowbell",
    "craftsman",
    "crayon",
    "credit",
    "cricket",
    "crocus",
    "cross",
    "crush",
    "cucumber",
    "cupcake",
    "curtain",
    "customer",
    "cyclone",
    "daffodil",
    "dance",
    "dash",
    "daughter",
    "deadline",
    "debt",
    "decimal",
    "deer",
    "delete",
    "dentist",
    "description",
    "desk",
    "detective",
    "diaphragm",
    "difference",
    "dill",
    "dinner",
    "direction",
    "discussion",
    "distance",
    "division",
    "dog",
    "dolphin",
    "donna",
    "doubt",
    "drain",
    "drawbridge",
    "dress",
    "drink",
    "drizzle",
    "dry",
    "dugout",
    "ear",
    "east",
    "editorial",
    "effect",
    "egypt",
    "elephant",
    "employee",
    "enemy",
    "engineering",
    "environment",
    "equipment",
    "ethernet",
    "evening",
    "exchange",
    "existence",
    "explanation",
    "eyelash",
    "fact",
    "fall",
    "farm",
    "father-in-law",
    "feather",
    "feedback",
    "female",
    "fertilizer",
    "fiction",
    "fighter",
    "finger",
    "fireman",
    "fisherman",
    "flat",
    "flight",
    "flower",
    "foam",
    "food",
    "force",
    "forgery",
    "fortnight",
    "fox",
    "france",
    "freighter",
    "friday",
    "front",
    "fuel",
    "gallon",
    "garden",
    "gate",
    "gear",
    "gender",
    "george",
    "ghana",
    "girdle",
    "glider",
    "glue",
    "goldfish",
    "good-bye",
    "gosling",
    "grain",
    "grandmother",
    "grass",
    "great-grandfather",
    "green",
    "grip",
    "growth",
    "guilty",
    "gym",
    "hair",
    "halibut",
    "hammer",
    "handicap",
    "hardboard",
    "harmonica",
    "hate",
    "headline",
    "heat",
    "helen",
    "helmet",
    "heron",
    "himalayan",
    "hobbies",
    "holiday",
    "hook",
    "hose",
    "hourglass",
    "hubcap",
    "hyacinth",
    "hyena",
    "icicle",
    "illegal",
    "inch",
    "india",
    "innocent",
    "instrument",
    "interest",
    "invention",
    "iraq",
    "israel",
    "jaguar",
    "january",
    "jasmine",
    "jeep",
    "jennifer",
    "john",
    "journey",
    "july",
    "june",
    "kale",
    "karen",
    "kenya",
    "kevin",
    "kick",
    "kimberly",
    "kitten",
    "knife",
    "kohlrabi",
    "ladybug",
    "lan",
    "larch",
    "lathe",
    "law",
    "leaf",
    "leg",
    "leo",
    "level",
    "lier",
    "lilac",
    "line",
    "lip",
    "lisa",
    "liver",
    "loan",
    "locust",
    "love",
    "lunchroom",
    "luttuce",
    "lyre",
    "macrame",
    "maid",
    "makeup",
    "mallet",
    "manicure",
    "maraca",
    "margin",
    "market",
    "mask",
    "mattock",
    "measure",
    "meeting",
    "menu",
    "meteorology",
    "mexico",
    "microwave",
    "milkshake",
    "mimosa",
    "mini-skirt",
    "mirror",
    "mitten",
    "mom",
    "month",
    "mosque",
    "motion",
    "mouse",
    "multi-hop",
    "music",
    "nail",
    "narcissus",
    "needle",
    "nerve",
    "news",
    "nickel",
    "nitrogen",
    "north",
    "nose",
    "novel",
    "nurse",
    "oatmeal",
    "occupation",
    "octave",
    "offence",
    "okra",
    "opera",
    "option",
    "order",
    "ornament",
    "output",
    "overcoat",
    "oxygen",
    "page",
    "pair",
    "pamphlet",
    "panda",
    "pantry",
    "paper",
    "parcel",
    "parrot",
    "partner",
    "passenger",
    "pastor",
    "patient",
    "payment",
    "peanut",
    "peen",
    "penalty",
    "peony",
    "period",
    "persian",
    "pet",
    "philosophy",
    "piccolo",
    "pig",
    "pilot",
    "ping",
    "pisces",
    "plane",
    "plaster",
    "platinum",
    "pleasure",
    "plow",
    "point",
    "policeman",
    "polo",
    "poppy",
    "port",
    "postage",
    "poultry",
    "precipitation",
    "price",
    "prison",
    "produce",
    "profit",
    "prose",
    "pruner",
    "puffin",
    "pumpkin",
    "purchase",
    "pvc",
    "quality",
    "queen",
    "quill",
    "quiver",
    "racing",
    "radish",
    "rain",
    "rake",
    "rat",
    "ray",
    "reason",
    "recorder",
    "refrigerator",
    "relation",
    "reminder",
    "representative",
    "responsibility",
    "retailer",
    "rhinoceros",
    "riddle",
    "risk",
    "roadway",
    "rock",
    "romania",
    "room",
    "rotate",
    "rub",
    "run",
    "ruth",
    "sailboat",
    "sale",
    "sampan",
    "sandwich",
    "satin",
    "sausage",
    "scale",
    "scarf",
    "school",
    "scorpio",
    "screw",
    "seal",
    "season",
    "secure",
    "segment",
    "semicircle",
    "separated",
    "session",
    "shake",
    "shape",
    "shears",
    "shell",
    "shirt",
    "shop",
    "show",
    "siberian",
    "sidewalk",
    "silk",
    "single",
    "size",
    "skin",
    "slave",
    "slice",
    "slope",
    "smoke",
    "snow",
    "snowplow",
    "society",
    "sofa",
    "soil",
    "soprano",
    "sousaphone",
    "soy",
    "spaghetti",
    "sparrow",
    "sphere",
    "spinach",
    "spot",
    "spy",
    "squirrel",
    "star",
    "statement",
    "steel",
    "step-brother",
    "step-grandfather",
    "step-sister",
    "steven",
    "stitch",
    "stone",
    "stopwatch",
    "stove",
    "street",
    "structure",
    "substance",
    "suede",
    "summer",
    "sunflower",
    "support",
    "surprise",
    "swamp",
    "sweatshop",
    "swimming",
    "sword",
    "syrup",
    "tabletop",
    "tailor",
    "tanker",
    "taurus",
    "tea",
    "technician",
    "temper",
    "tendency",
    "territory",
    "texture",
    "thermometer",
    "thought",
    "throne",
    "thursday",
    "tights",
    "timer",
    "tire",
    "toast",
    "tomato",
    "tooth",
    "tornado",
    "tower",
    "trade",
    "tramp",
    "trapezoid",
    "trial",
    "trip",
    "trout",
    "trunk",
    "tuba",
    "tuna",
    "turn",
    "turtle",
    "twine",
    "uganda",
    "uncle",
    "underwear",
    "use",
    "vacuum",
    "vase",
    "veil",
    "venezuelan",
    "vessel",
    "vietnam",
    "violet",
    "vise",
    "volcano",
    "waiter",
    "wallaby",
    "warm",
    "waste",
    "waterfall",
    "wealth",
    "wedge",
    "week",
    "whip",
    "wholesaler",
    "willow",
    "windscreen",
    "winter",
    "withdrawal",
    "women",
    "word",
    "wound",
    "wrinkle",
    "yacht",
    "yarn",
    "yogurt",
    "zephyr",
    "zoo"
};

int buffer[2][2] = {
    {EMPTY, START}, // char, pos
    {EMPTY, START}
};

// Set the pins to use for output.
void pins() {
    Rb.init();
}

// Words.
void render() {
    
    if (buffer[0][0] == EMPTY) {
        buffer[0][0] = getNextFromQueue();
    } else if (buffer[1][0] == EMPTY && buffer[0][1] == 0) {
        buffer[1][0] = getNextFromQueue();
    }

    if (buffer[0][1] == END) {
        buffer[0][0] = EMPTY;
        buffer[0][1] = START;
    }

    if (buffer[0][0] > EMPTY) {
        Rb.drawChar(buffer[0][0], buffer[0][1], 0, color);
        buffer[0][1]--;
    }

    if (buffer[1][1] == END) {
        buffer[1][0] = EMPTY;
        buffer[1][1] = START;
    }

    if (buffer[1][0] > EMPTY) {
        Rb.drawChar(buffer[1][0], buffer[1][1], 0, color);
        buffer[1][1]--;
    }

    delay(160);

    Rb.blankDisplay();
}

// Standard setup function.
void setup() {
    pins();
    Serial.begin(9600);
    addStringToQueue("Hello");
    timer.setInterval(10000, randomWords);
}

void randomWords() {
    int r = rand() % 4;
    addStringToQueue(WORDS[r]);
//    Serial.write(WORDS[r]);
}

int getNextFromQueue() {
    if (lastAdded == lastRead) {
        return 0;
    }
    lastRead++;
    if (lastRead >= 256) {
        lastRead = 0;
    }
    return queue[lastRead];
}

void addCharToQueue(char c) {
    lastAdded++;
    if (lastAdded >= 256) {
        lastAdded = 0;
    }
    queue[lastAdded] = c;
}

void addStringToQueue(char *string) {
    for(int i = 0; i < strlen(string); i++) {
        addCharToQueue(string[i]);
    }
}

// Standard loop function.
void loop() {
    timer.run();
    if (Serial.available() > 0) {
        addCharToQueue(Serial.read());
    }
    render();
}

